version: "3.9"

volumes:
    scripts:
    mssqlserver:  
    mssqluser:

services:
  db1:
    build: .
    ports:
     - "1433:1433"
    environment:
      - SA_PASSWORD=Password1?
    volumes:
      - mssqlserver:/var/opt/mssql
      - mssqluser:/var/opt/sqlserver
      - ./scripts:/scripts 
